// Explicit release allowlist shared by build and static checks. Local data never ships.
export const extensionFiles = [
  "manifest.json",
  "src/background.js",
  "src/content/page-observer.js",
  "src/content/x-client.js",
  "src/content/content.js",
  "src/content/content.css",
  "src/content/overlay.css",
  "src/manager/manager.html",
  "src/manager/manager.js",
  "src/manager/manager.css",
  "src/lib/core.js",
  "src/lib/store.js",
  "src/lib/jev.js",
  "src/lib/jev-cache.js",
  "src/lib/x-block.js",
  "assets/brand.svg",
  "assets/icons/icon-16.png",
  "assets/icons/icon-20.png",
  "assets/icons/icon-24.png",
  "assets/icons/icon-32.png",
  "assets/icons/icon-48.png",
  "assets/icons/icon-64.png",
  "assets/icons/icon-128.png",
  "LICENSE",
];
